neo4jdb:
  url: bolt://localhost:7687
  username: neo4j
  password: 123./\.abc

chromadb:
  chroma_db_impl: duckdb+parquet
  persist_directory: ./data/chroma/

extractor:
  arxiv:
    data_path: ./data/arxiv/

llm:
  model_name: gpt-3.5-turbo
  temperature: 0.3