topic: network science # should be changed for new topic

neo4jdb:
  url: bolt://localhost:7687
  username: neo4j
  password: 123./\.abc

chromadb:
  chroma_db_impl: duckdb+parquet
  persist_directory: ./data/chroma/
  collection_name: arxiv1 # should be changed for new topic
  distance_function: l2

extractor:
  arxiv:
    data_path: ./data/arxiv/
    vs_key_info:
      embedding_key: summary
      # id_key: uuid
      metadata_keys: [title]
  entity:
    vs_key_info:
      embedding_key: description
      # id_key: uuid
      metadata_keys: [name, general, type]

llm:
  model_name: gpt-3.5-turbo
  temperature: 0.3

shortenings:
  Paper: p
  Concept: c
  Model: m
  Dataset: d