[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "AutoKGC"
version = "0.0.3"
description = "Automatic Knowledge Graph Construction"
authors = ["Hao Chen"]
license = "MIT"
readme = "README.md"
include = ["AutoKGC"]
scripts = { autokgc = "AutoKGC.scripts.cli:main" }

[tool.poetry.dependencies]
python = "^3.7"
argparse = "*"
pyyaml = "*"
chroma = "*"
neo4j = "*"
langchain = "*"
tqdm = "*"
pydantic = "1.10.8"
