version: '3'
services:
  neo4j:
    image: neo4j
    stdin_open: true
    tty: true
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - /data:/data
    environment:
      NEO4J_apoc_export_file_enabled: true
      NEO4J_apoc_import_file_enabled: true
      NEO4J_apoc_import_file_use__neo4j__config: true
      NEO4J_AUTH: "neo4j/hello_neo4j"
      NEO4J_PLUGINS: "[\"apoc\"]"