name: Build Docs

on: 
  push:
    branches:
      - main

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sphinx sphinx-rtd-theme
        pip install furo
    - name: Generate docs
      run: |
        cd docs
        sphinx-apidoc --module-first -f -o source ./DescKGC
        cd ..
    - name: Build docs
      run: |
        cd docs
        make clean
        make html
        cd ..
    - name: Deploy docs
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/build/html